function plottracks(tracks,minlength)
%
%PLOTTRACKS(TRACKS)
%
%TRACKS is the resulting particle trajectories generated by the MFM
%particle tracking algorithm.  Each .h5 file will have a corresponding .mat
%file containing the appropriate track data.  Simply click and drag this 
%file into the Matlab workspace and run this function.
%

if nargin<2
    minlength = 0;
end

numtracks = length(tracks);
for a = 1:numtracks
    if size(tracks{a},1) >= minlength
        plot3(tracks{a}(:,2),tracks{a}(:,1),tracks{a}(:,3),'color',0.5*rand(1,3)+0.5,'LineWidth',1.5); hold on
        axis('equal');
    end
end
    